name: google_services
description: "Project for google services."
version: 0.0.4
publish_to: none
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  retrofit: ^4.4.2
  http_parser: ^4.1.2
  injectable: ^2.2.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  logger: ^2.5.0
  flutter_bloc: ^9.1.0
  platform_identity:
    git:
      url: https://github.com/SalemZakkar/platform_identity.git
  go_router: ^15.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.2
  flutter_gen: ^5.10.0
  injectable_generator: ^2.7.0
  retrofit_generator: ^9.1.9
